driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7
  - name: redhat-7
  - name: scientific-7
  - name: oracle-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
 - name: default
   run_list:
   - recipe[test::default]
   attributes:
      oink_code: <%= ENV['SNORT_LICENCE'] %>
      community_rules_url: <%= ENV['COMMUNITY_URL'] %>
