---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      - kitchen/dokken-single:
          name: default-amazonlinux-2
          suite: default
          platform: amazonlinux-2
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-8
          suite: default
          platform: debian-8
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default
          platform: debian-9
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-14.04
          suite: default
          platform: ubuntu-14.04
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-16.04
          suite: default
          platform: ubuntu-16.04
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-18.04
          suite: default
          platform: ubuntu-18.04
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default
          platform: centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-26
          suite: default
          platform: fedora-26
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-27
          suite: default
          platform: fedora-27
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-latest
          suite: default
          platform: fedora-latest
          requires:
            *lint_and_unit
